title: Joshua's Professional Journey
description: A detailed account of my professional experiences, skills, and accomplishments.
baseurl: "/About-Me" # the subpath of your site
url: "https://jlamb4.github.io" # the base hostname & protocol for your site

theme: alembic-jekyll-theme

# Other configuration options